### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by SubhrajitPrusty**
- added badges
- added screenshots
- added playstore link

### CODE REVIEW

**Comment by mojito9542** [comment]
can you change the "built for android" badge?

**Comment by SubhrajitPrusty** [comment]
> can you change the build for android badge?

what do you mean by build?

**Comment by mojito9542** [comment]
See now

**Comment by SubhrajitPrusty** [comment]
> See now

yes. What do you want it to be?

**Comment by mojito9542** [comment]
Not red , anything else and a little smaller

**Comment by SubhrajitPrusty** [comment]
Like this?

**Comment by mojito9542** [comment]
Cool

**Pull request merged**
